### ISSUE TITLE
game crashes before launching

### ISSUE THREAD

**Issue by giovuddu** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#49] opened 2024-03-09 18:44 UTC
### Minecraft Version

1.20.1

### Describe the Bug

The game won't even start, it crashes imediately, i don't know where is the issue, i think it's becouse of the new create 1.5.1f.
i'm using fabric 0.15.7

### Reproduction Steps

launch the game

### Expected Result

the game launches

### Crash Report or Log

https://pastebin.com/DTSeJGkv

### Other Mods

other mods are written in the log

### Mod Version

1.2.14

**Comment by IThundxr** [comment] 2024-03-09 19:22
Duplicate of #47

**Closed as completed** 2024-03-09 19:22 UTC
Labels: bug
