### ISSUE TITLE
Crash after killing a mob with an sword using deployer

### ISSUE THREAD

**Issue by DefomCode** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#33] opened 2023-12-03 03:07 UTC
### Minecraft Version

1.20.1

### Describe the Bug

I am pit a deployer with a sword, put mob in his way and game crashed. 

I think this bug is somehow related to the drop that falls from the mob, and more specifically with pieces of experience. Perhaps their number is incorrectly calculated and minecraft is trying to remember not the whole part, but a natural number (for example, there are 1.6 pieces of experience) and the origin of the game's departure. This is just my guess, I'm not saying that this is the problem.

* mod version 1.2.9 - CEI 1.2.9 for Create 1.20.1-0.5.1-d-build.1161+mc1.20.1

### Reproduction Steps

1. Put a deployer with a sword
2. Put a mob in his way
3. deployer kills a mob
4. crash game
5. You can't enter the world anymore. crashes on entry
...

### Expected Result

I am put deployer with a sword, put mob in his way and game not crashed. deployer drops items using chute  (mob loot and experience)

### Other Mods

* Fabric API
* Cloth Config API
* Fabric Language Kotlin
* Architectury API
* Sodium
* Create Fabric Sodium Fix
* Create Crafts & Additions
* CreateFabric&REIBugFix
* Create: Steam 'n' Rails
* Create: New Age
* Create mod Trims
* Create Jetpack
* Create: Broken Bad
* Emotecraft
* Roughly Enough Items (REI)
* No Chat Reports
* Carry On
* Botarium
* Artifacts

### Mod Version

1.2.9

**Comment by IThundxr** [comment] 2023-12-03 03:30
Post a log, and the issue is most likely on create fabric's side since swords in deployers are known to crash games at the moment

**Comment by DefomCode** [comment] 2023-12-03 11:38
> Post a log, and the issue is most likely on create fabric's side since swords in deployers are known to crash games at the moment

[latest.log](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/files/13538789/latest.log)

**Comment by DefomCode** [comment] 2023-12-03 11:41
[crash-2023-12-03_14.37.41-server.txt](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/files/13538793/crash-2023-12-03_14.37.41-server.txt)

**Comment by NolanHewitt** [comment] 2023-12-15 09:16
Same issue here. World got bricked, thankfully it was just a creative test world.

**Comment by IThundxr** [comment] 2023-12-15 11:39
Yep it's a create sided error, will be fixed in patch f

**Closed as completed by IThundxr** 2023-12-15 11:39 UTC
Labels: bug
