### ISSUE TITLE
XP Nugget and chunk of experience give very little xp

### ISSUE THREAD

**Issue by ST-DDT** [DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric-Legacy#31] opened 2023-12-01 16:52 UTC
### Minecraft Version

1.20.1

### Describe the Bug

When eating a nugget of experience I get 3xp. When I put the nugget of expierence on the disenchanter I get next to no exp.
1 stack eaten = 192 exp/mB
1 stack disenchanted = 2exp/mB

### Reproduction Steps

1. Build a disenchanter
2. Eat a stack of nuggets of experience
3. Drain yourself on the disenchanter
4. Look at the tank
5. See 192 mB of xp ✔
6. Destroy/empty the tank
7. Put a stack of nuggets of experience on the disenchanter
8. Look at the tank
9. See 2 mB of xp in the tank ⚠️

### Expected Result

See 192 mB of xp in the tank in both cases.

### Screenshots and Videos

[CEI-bug.webm](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/1579362/d8c4f633-f829-4242-9b28-f5873d4445fd)

![grafik](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/1579362/eaab55f4-cd59-4cb7-9284-473a8fcbe334)
![grafik](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/1579362/3b1c53c1-9a39-486b-8c6b-7cd14f0e74c5)
![grafik](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/1579362/d36ea464-c91c-4d19-ae4f-541f7693f619)
![grafik](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/1579362/5948b64f-2c83-4434-b48f-e7695a98f367)
![grafik](https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry-Fabric/assets/1579362/e1423fb9-6e2e-42bf-ae9e-6a410777207a)

### Other Mods

- create_enchantment_industry-1.2.8.jar
- create-fabric-0.5.1-d-build.1161+mc1.20.1.jar
- fabric-api-0.88.1+1.20.1.jar
- sodium-fabric-mc1.20-0.4.10+build.27.jar

(it is reproducible with only those 4 mods, but I usually have way more)

### Mod Version

1.2.8

**Comment by IThundxr** [comment] 2023-12-01 17:08
For myself: issue is fabric uses droplets, multiply these the output of these recipes by 81

**Comment by ST-DDT** [comment] 2023-12-01 17:14
Do you accept monetary donations to thank you for maintaining this mod?
If yes, please post a link (preferably PayPal or Patreon).

**Comment by IThundxr** [comment] 2023-12-01 17:17
> Do you accept monetary donations? If yes, please post a link (preferably PayPal or Patreon).

Yes [kofi](https://ko-fi.com/IThundxr)

**Comment by ST-DDT** [comment] 2023-12-01 17:20
Thanks for your work ❤️

**Comment by IThundxr** [comment] 2023-12-02 03:26
Fixed in 1.2.9

Open another issue if you find anything else that's not working as intended ^^

**Closed as completed** 2023-12-02 03:27 UTC
Labels: bug
